#values = input("Input some comma seprated numbers : ")
#list = values.split(",")
#tuple = tuple(list)
#print('List : ',list)
#print('Tuple : ',tuple)

values = input('Please input some comma seperated numbers')
list = values.split(",")
tuple = tuple(list)
print ('list : ',list)
print('tuple : ',tuple)
